import { useCallback, useEffect, useState } from "react";
import { useLang } from "../i18n/LanguageContext.jsx";
import { getUser } from "./userAuth.js";
import { fetchReviews, createReview, uploadReviewPhotos } from "../data/reviews.js";

function Stars({ value, onSelect }) {
  return (
    <span className="stars-input">
      {[1, 2, 3, 4, 5].map((n) => (
        <button key={n} type="button" className={n <= value ? "on" : ""}
                onClick={onSelect ? () => onSelect(n) : undefined} tabIndex={onSelect ? 0 : -1} aria-label={`${n}★`}>★</button>
      ))}
    </span>
  );
}

export default function Reviews({ product }) {
  const { t, lang } = useLang();
  const [state, setState] = useState({ reviews: [], count: 0, average: null, status: "loading" });
  const [name, setName] = useState("");
  const [rating, setRating] = useState(5);
  const [text, setText] = useState("");
  // Kept as Files (not data URIs): they are uploaded on submit and the preview
  // is a temporary object URL, so a 4 MB photo never sits in React state twice.
  const [photos, setPhotos] = useState([]);
  const [submitting, setSubmitting] = useState(false);
  const [err, setErr] = useState("");
  const [thanks, setThanks] = useState(false);

  const handle = product.slug;

  const load = useCallback(async () => {
    try {
      const res = await fetchReviews(handle);
      setState({ ...res, status: "ready" });
    } catch {
      // The product page must still render without its reviews.
      setState({ reviews: [], count: 0, average: null, status: "error" });
    }
  }, [handle]);

  useEffect(() => { load(); }, [load]);

  const submit = async (e) => {
    e.preventDefault();
    if (!text.trim() || submitting) return;
    setErr(""); setSubmitting(true);
    const u = getUser();
    try {
      // Photos first. If they fail we surface it and stop, rather than posting a
      // review that silently lost the pictures the customer chose.
      const photoUrls = photos.length ? await uploadReviewPhotos(photos.map((p) => p.file)) : [];
      await createReview({
        handle,
        rating,
        body: text.trim(),
        authorName: name.trim() || (u && u.email) || t("rev.anon"),
        authorEmail: (u && u.email) || null,
        locale: lang,
        photoUrls,
      });
      photos.forEach((p) => URL.revokeObjectURL(p.url));
      setPhotos([]);
      setName(""); setText(""); setRating(5);
      setThanks(true); setTimeout(() => setThanks(false), 2500);
      // Re-read rather than splice locally: the server owns the average, and
      // guessing it here is how the two drift apart.
      await load();
    } catch (e2) {
      setErr(e2?.message ? String(e2.message) : t("rev.error"));
    }
    setSubmitting(false);
  };

  // Only real reviews count. With none, we say so instead of printing a rating
  // nobody gave — the number shown here used to be generated by the scraper.
  const hasReviews = state.count > 0 && state.average != null;

  return (
    <section className="section reviews">
      <h2 className="section-title">{t("rev.title")}</h2>
      <div className="rev-summary">
        {hasReviews ? (
          <div className="rev-avg">
            <b>{state.average.toFixed(1)}</b>
            <Stars value={Math.round(state.average)} />
            <small>{state.count} {t("rev.based")}</small>
          </div>
        ) : (
          <p className="muted">{state.status === "loading" ? "…" : t("rev.none")}</p>
        )}
      </div>

      <form className="rev-form" onSubmit={submit}>
        <h3>{t("rev.write")}</h3>
        <div className="rev-row">
          <label>{t("rev.your")}: <Stars value={rating} onSelect={setRating} /></label>
        </div>
        <input className="rev-name" placeholder={t("rev.name")} value={name} onChange={(e) => setName(e.target.value)} />
        <textarea className="rev-text" placeholder={t("rev.text")} value={text} onChange={(e) => setText(e.target.value)} rows={3} />
        <div className="rev-photos">
          {photos.map((p, i) => (
            <span key={p.url} style={{ position: "relative" }}>
              <img src={p.url} alt="" className="rev-photo" />
              <button type="button" className="panel-x" style={{ position: "absolute", top: -6, right: -6 }}
                      onClick={() => setPhotos((ph) => { URL.revokeObjectURL(p.url); return ph.filter((_, j) => j !== i); })}>×</button>
            </span>
          ))}
          {photos.length < 3 && (
            <label className="rev-photo-add">📷 {t("rev.photo")}
              <input type="file" accept="image/jpeg,image/png,image/webp" multiple
                     onChange={(e) => {
                       const picked = Array.from(e.target.files || []).map((file) => ({ file, url: URL.createObjectURL(file) }));
                       setPhotos((ph) => [...ph, ...picked].slice(0, 3));
                       e.target.value = "";
                     }} />
            </label>
          )}
        </div>
        <button className="btn btn-primary" type="submit" disabled={submitting || !text.trim()}>
          {submitting ? <><span className="btn-spin" aria-hidden="true" /> {t("rev.sending")}</> : t("rev.submit")}
        </button>
        {err && <span className="rev-err">{err}</span>}
        {thanks && <span className="rev-thanks">✓ {t("rev.thanks")}</span>}
      </form>

      <div className="rev-list">
        {state.reviews.length === 0 ? (
          <p className="muted">{t("rev.none")}</p>
        ) : state.reviews.map((r) => (
          <div key={r.id} className="rev-item">
            <div className="rev-item-head">
              <b>{r.author_name}</b>
              <Stars value={r.rating} />
              <small className="muted">{r.created_at.slice(0, 10)}</small>
            </div>
            <p>{r.body}</p>
            {r.photo_urls && r.photo_urls.length > 0 && (
              <div className="rev-thumbs">{r.photo_urls.map((u) => <img key={u} src={u} alt="" />)}</div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}
