/**
 * The fixed pilot cohort: 70 frames the generation pipeline is shaken out on
 * before it is ever pointed at the whole catalogue.
 *
 * Generated by `scripts/build-pilot-set.mjs` and committed, so the cohort is
 * reproducible and a `git diff` shows exactly which frames entered or left.
 * The rationale — why these brands, why it over-samples rimless and transparent
 * frames, why 20% is reserved for easy controls — is in
 * docs/frame-media-generation.md, Appendix B.
 */
import pilot from "./frame-media-pilot.json";

export interface PilotFrame {
  sku: string;
  /** Medusa handle. The one enqueue must use — NOT `seed_slug`. */
  handle: string;
  /** Storefront seed slug. Present only so a human can find the frame locally. */
  seed_slug: string;
  brand: string;
  /** Supplier collection slug — `simply-lite`, `4u`. NOT a slugified brand name. */
  brand_slug: string;
  colorways: string[];
  colorway_count: number;
  shape: string | null;
  material: string[];
  style: string | null;
  difficulty: number;
  tags: string[];
  selected_because: string;
}

export const PILOT_FRAMES = pilot.frames as PilotFrame[];

/** Every handle in the cohort. */
export const PILOT_HANDLES: string[] = PILOT_FRAMES.map((f) => f.handle);

/** Totals, straight from the manifest, so nothing recomputes them differently. */
export const PILOT_TOTALS = pilot.totals as {
  frames: number;
  colorways: number;
  views: number;
  by_brand: Record<string, { frames: number; colorways: number }>;
};

/**
 * Handles for one brand of the cohort — the tier-1 run, which does Simplylite
 * first because it is the hardest: rimless titanium has no rim to anchor
 * identity and transparent lenses vanish into the white packshot background.
 * If prompts need rewriting, finding out costs 120 views instead of 608.
 */
export function pilotHandlesForBrand(brand: string): string[] {
  // Accepts either the display name ("Simplylite") or the supplier slug
  // ("simply-lite"), because the two do not agree and both are things a person
  // reasonably types. "Four You" vs "4u" is the case that makes guessing hopeless.
  const wanted = brand.trim().toLowerCase().replace(/\s+/g, "-");
  return PILOT_FRAMES.filter(
    (f) =>
      f.brand.toLowerCase().replace(/\s+/g, "-") === wanted ||
      f.brand_slug.toLowerCase() === wanted
  ).map((f) => f.handle);
}

/** The two calibration frames: hardest in the cohort, and an ordinary control. */
//
// NOTE the brand slug: the supplier's collection for Simplylite is `simply-lite`,
// with a hyphen, so the handle is `sl107-simply-lite`. Writing the brand NAME
// here instead would look right and match nothing.
export const CALIBRATION_HANDLES = ["sl107-simply-lite", "dc-50-di-caprio"];

/**
 * The reserved controls: the EASIEST frames in the cohort — opaque acetate, full
 * frame, plain colours.
 *
 * They are measured separately from the overall pass rate on purpose. A cohort
 * that over-samples rimless and transparent frames (which this one does, by
 * design) can hide a regression on ordinary frames inside a good-looking average
 * — and ordinary frames are 90% of the catalogue and 90% of the bill. If the
 * easy ones fail, the problem is the pipeline, not the frames.
 */
export const PILOT_CONTROL_HANDLES: string[] = PILOT_FRAMES.filter((f) =>
  f.selected_because.startsWith("control")
).map((f) => f.handle);
